In [1]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB

In [2]:
new_data = pd.read_csv('salidas.csv')
new_data.head()

tip_naci  mes_movi  dia_movi  via_tran  mot_viam  AMER_SAMOA  ANGUILLA  \
0         1        12         8         2         5           0         0   
1         1        10         3         1         1           0         0   
2         1        10        24         2         1           0         0   
3         1         9        22         1         1           0         0   
4         1         4         8         1         1           0         0   

   ARUBA  BELARUS  BENIN  ...  URUGUAY  USA  USVIRGIN_IS  UZBEKISTAN  VANUATU  \
0      0        0      0  ...        0    0            0           0        0   
1      0        0      0  ...        0    1            0           0        0   
2      0        0      0  ...        0    0            0           0        0   
3      0        0      0  ...        0    0            0           0        0   
4      0        0      0  ...        0    1            0           0        0   

   VENEZUELA  VIET_NAM  YEMEN  ZAMBIA  ZIMBABWE  
0          0         0      0       0         0  
1          0         0      0       0         0  
2          0         0      0       0         0  
3          0         0      0       0         0  
4          0         0      0       0         0  

[5 rows x 174 columns]

In [3]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2488532 entries, 0 to 2488531
Columns: 174 entries, tip_naci to ZIMBABWE
dtypes: int64(174)
memory usage: 3.2 GB


In [4]:
# convert to categorical
new_data['mot_viam'] = new_data['mot_viam'].astype('category')

In [5]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2488532 entries, 0 to 2488531
Columns: 174 entries, tip_naci to ZIMBABWE
dtypes: category(1), int64(173)
memory usage: 3.2 GB


In [6]:
new_data.head()

tip_naci  mes_movi  dia_movi  via_tran mot_viam  AMER_SAMOA  ANGUILLA  \
0         1        12         8         2        5           0         0   
1         1        10         3         1        1           0         0   
2         1        10        24         2        1           0         0   
3         1         9        22         1        1           0         0   
4         1         4         8         1        1           0         0   

   ARUBA  BELARUS  BENIN  ...  URUGUAY  USA  USVIRGIN_IS  UZBEKISTAN  VANUATU  \
0      0        0      0  ...        0    0            0           0        0   
1      0        0      0  ...        0    1            0           0        0   
2      0        0      0  ...        0    0            0           0        0   
3      0        0      0  ...        0    0            0           0        0   
4      0        0      0  ...        0    1            0           0        0   

   VENEZUELA  VIET_NAM  YEMEN  ZAMBIA  ZIMBABWE  
0          0         0      0       0         0  
1          0         0      0       0         0  
2          0         0      0       0         0  
3          0         0      0       0         0  
4          0         0      0       0         0  

[5 rows x 174 columns]

In [7]:
y = new_data['mot_viam']  #variable target
X = new_data.drop(columns=['mot_viam'])  #variables input

In [8]:
from sklearn.model_selection import train_test_split
train_X, valid_X, train_y, valid_y = train_test_split(X, y, test_size=0.4, random_state=1)

In [9]:
# run naive Bayes
bayes = MultinomialNB(alpha=0.01)
bayes.fit(train_X, train_y)

# predict probabilities
predProb_train = bayes.predict_proba(train_X)
predProb_valid = bayes.predict_proba(valid_X)

# predict class membership
y_train_pred = bayes.predict(train_X)
y_valid_pred = bayes.predict(valid_X)

In [10]:
from metric import classificationSummary
classificationSummary(train_y, y_train_pred)

Confusion Matrix (Accuracy 0.6458)

       Prediction
Actual      0      1      2      3      4      5      6      7
     0 422050      0      6     41 218239      0     52     27
     1   6657      3      2      0   4187      0      1      6
     2  19389      0     35      5  23984      0     33     18
     3   3597      0      9    241   9059      0     54      1
     4 164124      1     17     95 541614      0     99     17
     5    115      0      0      0    108      0      0      0
     6  10091      0      0      6   3036      0    111      6
     7  42148      1     10     33  23607      0     32    152


In [11]:
classificationSummary(valid_y, y_valid_pred)

Confusion Matrix (Accuracy 0.6450)

       Prediction
Actual      0      1      2      3      4      5      6      7
     0 279577      0      4     32 146375      1     28     14
     1   4562      0      0      1   2762      0      2      7
     2  12742      0     16      7  15945      1     16     11
     3   2478      0      3    157   6194      0     42      0
     4 109181      2     15     71 362119      1     65     24
     5     91      0      0      0     60      0      0      0
     6   6821      0      0      3   1989      0    101      8
     7  27947      2      5     21  15786      0     21    103


In [12]:
columns = [
    'tip_naci', 'mes_movi', 'dia_movi', 'via_tran', 'mot_viam',
    'AMER_SAMOA', 'ANGUILLA', 'ARUBA', 'BELARUS', 'BENIN', 'BULGARIA',
    'BURKINA_FASO', 'BURUNDI', 'CAMBODIA', 'CAMEROON', 'CANADA',
    'CAPE_VERDE', 'CAYMAN_IS', 'CENT_AFR_REP', 'CHAD', 'CHILE',
    'CHINA', 'COLOMBIA', 'CONGO', 'COSTA_RICA', 'COTE_DIVOIRE',
    'CROATIA', 'CUBA', 'CYPRUS', 'CZECH_REP', 'DENMARK', 'DJIBOUTI',
    'DOMINICA', 'DOMINICAN_RP', 'D_RP_CONGO', 'EGYPT', 'EL_SALVADOR',
    'EQ_GUINEA', 'ESTONIA', 'ETHIOPIA', 'FALKLAND_IS', 'FIJI', 'FINLAND',
    'FRANCE', 'FR_GUIANA', 'FR_POLYNESIA', 'GABON', 'GAMBIA', 'GEORGIA',
    'GERMANY', 'GHANA', 'GREECE', 'GRENADA', 'GUADELOUPE', 'GUATEMALA',
    'GUINEA', 'GUINEABISSAU', 'GUYANA', 'HAITI', 'HONDURAS', 'HONGKONG_SAR',
    'HUNGARY', 'ICELAND', 'INDIA', 'INDONESIA', 'IRAN', 'IRAQ', 'IRELAND',
    'ISRAEL', 'ITALY', 'JAMAICA', 'JAPAN', 'JORDAN', 'KAZAKHSTAN', 'KENYA',
    'KIRIBATI', 'KOREA_NORTE', 'KOREA_SUR', 'KUWAIT', 'KYRGYZTAN', 'LATVIA',
    'LEBANON', 'LESOTHO', 'LIBERIA', 'LIBYA', 'LIECHTENSTEN', 'LITHUANIA',
    'LUXEMBOURG', 'MADAGASCAR', 'MALASIA', 'MALAWI', 'MALDIVES', 'MALI',
    'MALTA', 'MARSHALL_IS', 'MARTINIQUE', 'MAURITANIA', 'MAURITIUS',
    'MEXICO', 'MICRONESIA', 'MONACO', 'MONGOLIA', 'MOROCCO', 'MOZAMBIQUE',
    'MYANMAR', 'NAMIBIA', 'NEPAL', 'NETHERLANDS', 'NEW_ZEALAND', 'NICARAGUA',
    'NIGER', 'NIGERIA', 'NORWAY', 'OMAN', 'PAKISTAN', 'PANAMA', 'PAPUA_NGUIN',
    'PARAGUAY', 'PERU', 'PHILIPPINES', 'POLAND', 'PORTUGAL', 'PUERTO_RICO',
    'QATAR', 'REP_MOLDOVA', 'ROMANIA', 'RUSSIAN_FED', 'RWANDA', 'SAMOA',
    'SAN_MARINO', 'SAUDI_ARABIA', 'SENEGAL', 'SEYCHELLES', 'SIERRA_LEONA',
    'SINGAPORE', 'SLOVAKIA', 'SLOVENIA', 'SOMALIA', 'SOUTH_AFRICA', 'SPAIN',
    'SRI_LANKA', 'ST_KITTS_NEV', 'ST_LUCIA', 'ST_VINCENT_G', 'SUDAN',
    'SURINAME', 'SWAZILAND', 'SWEDEN', 'SWITZERLAND', 'SYRIA', 'TAIWAN',
    'TAJIKISTAN', 'TANZANIA', 'TFYROM', 'THAILAND', 'TOGO', 'TRINIDAD_TBG',
    'TUNISIA', 'TURKEY', 'TURKS_CAICOS', 'UGANDA', 'UK', 'UKRAINE',
    'UNTD_ARAB_EM', 'URUGUAY', 'USA', 'USVIRGIN_IS', 'UZBEKISTAN', 'VANUATU',
    'VENEZUELA', 'VIET_NAM', 'YEMEN', 'ZAMBIA', 'ZIMBABWE'
]

mi_diccionario = {}

info = {
    "tip_naci": 1,
    "mes_movi": 7,
    "dia_movi": 20,
    "via_tran": 1,
    "USA": 1
}

for columna in columns:
    if columna == "mot_viam":
        continue
    if columna in info:
        mi_diccionario[columna] = info[columna]
    else:
        mi_diccionario[columna] = 0

df = pd.DataFrame([mi_diccionario])

input_data = df.to_numpy()

bayes.predict(input_data)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([5], dtype=int64)

In [13]:
mi_diccionario = {}

info = {
    "tip_naci": 1,
    "mes_movi": 12,
    "dia_movi": 3,
    "via_tran": 3,
    "PERU": 1
}

for columna in columns:
    if columna == "mot_viam":
        continue
    if columna in info:
        mi_diccionario[columna] = info[columna]
    else:
        mi_diccionario[columna] = 0

df = pd.DataFrame([mi_diccionario])

input_data = df.to_numpy()

bayes.predict(input_data)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [14]:
mi_diccionario = {}

info = {
    "tip_naci": 1,
    "mes_movi": 12,
    "dia_movi": 3,
    "via_tran": 3,
    "PERU": 1
}

for columna in columns:
    if columna == "mot_viam":
        continue
    if columna in info:
        mi_diccionario[columna] = info[columna]
    else:
        mi_diccionario[columna] = 0

df = pd.DataFrame([mi_diccionario])

input_data = df.to_numpy()

bayes.predict_proba(input_data)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([[5.21536320e-01, 6.32331531e-03, 5.79501768e-03, 2.40354020e-04,
        1.47141571e-01, 7.22830837e-04, 1.87278187e-01, 1.30962404e-01]])

In [15]:
mi_diccionario = {}

info = {
    "tip_naci": 1,
    "mes_movi": 2,
    "dia_movi": 3,
    "via_tran": 1,
    "USA": 1
}

for columna in columns:
    if columna == "mot_viam":
        continue
    if columna in info:
        mi_diccionario[columna] = info[columna]
    else:
        mi_diccionario[columna] = 0

df = pd.DataFrame([mi_diccionario])

input_data = df.to_numpy()

bayes.predict(input_data)

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([5], dtype=int64)

In [16]:
import pickle

output_model_file = 'model_bayes2.pkl'

with open(output_model_file, 'wb') as f:
    pickle.dump(bayes, f)